### ISSUE TITLE
Handle Admin disconnected

### ISSUE THREAD

**Issue by wowawiwa** [abustany/goretro#16]

**Comment by abustany** [comment]
This is already handled: the connection will end up dying after a given timeout, the participant will be removed from the room, and a new participant will be promoted as a host. There's an event for that (forgot the name, host changed or something). We might have to tune the timeout value though.

**Comment by wowawiwa** [comment]
okay

```
event: "host-changed"
​
payload: "Xb8MmfWrfZDlSptDM3CfbA=="
```
