### ISSUE TITLE
Receive Action Points when joining at state 3

### ISSUE THREAD

**Issue by wowawiwa** [abustany/goretro#17]

**Comment by abustany** [comment]
When joining in 'action points' state you should already get the full room with all the notes ?

**Comment by wowawiwa** [comment]
I see a `current-state` event with a room which notes map has keys but arrays are empty. Maybe I mutate by mistake but it doesn't seem so at first glance.

**Comment by zeusdeux** [comment]
In terms of the UI, it’d be cool to have all the notes in place when adding action items. Context and what not. 

By the way, awesome project! I love that it works on my phone!

**Comment by abustany** [comment]
> I see a `current-state` event with a room which notes map has keys but arrays are empty. Maybe I mutate by mistake but it doesn't seem so at first glance.

Hmm maybe this is broken on the backend side then :sweat_smile: I have a branch with some unit tests for the retro class which I'll push soon, I'll make sure this case is covered there.

**Comment by abustany** [comment]
Fixed in f9433011c3934f21b12e35e257a30638d8492ff1
